### ISSUE TITLE
Request for Improvement

### ISSUE THREAD

**Issue by princeeze** [mrdanieleze/Daniels-Bioinformatics-Codes#2]
Hello, some tips for improvement would be to firstly consider adding more comments to explain the purpose and functionality of specific parts of the code. And as for function parameters, instead of having `sequence_a` and `sequence_b` as global variables, it would be better to pass them as parameters to the `compare_dna_sequences_list` function. This makes the function more versatile and easier to use in different contexts.

Also try to implement some basic error handling. For instance, check if the provided sequences are non-empty before attempting to perform the sequence alignment.

Then the value 10 used for normalizing the score is a **magic number**. Consider making it a named constant or providing a brief comment explaining its significance. Why did you multiply by 10 specifically.

Lastly, the provided sequences (`sequence_a` and `sequence_b`) are empty. It would be beneficial to have example sequences or placeholders to illustrate how the function is intended to be used.

Cheers 👌

**Comment by mrdanieleze** [comment]
Hi Prince,

Thank you for taking the time to provide feedback and suggestions on the Genomic Sequence Comparison Code (GSCC). Your insights are valuable, and I appreciate your thorough review. I've implemented the recommended changes, including enhanced error handling, a named constant for score normalization, and additional comments for clarity. Feel free to check out the updated version and let me know if you have any further thoughts or suggestions.

Best regards.
